=== alcorpisces/OMS/web/WEB-INF/movies.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://learn.it.uts.edu.au/wsd"
           xmlns="http://learn.it.uts.edu.au/wsd"
           elementFormDefault="qualified">
    
    <xs:simpleType name="title">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z][a-zA-Z]*([ ][A-Z][a-zA-Z]*)*"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="movieReleaseDate">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{2}/[0-9]{2}/[0-9]{4}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="moviePrice">
        <xs:restriction base="xs:string">
            <xs:pattern value="$[0-9]*"/>
        </xs:restriction>
    </xs:simpleType>
    
     <xs:simpleType name="availableCopies">
        <xs:restriction base="xs:integer">
            <xs:pattern value="[0-9]*"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="movies">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="movie" minOccurs="0" maxOccurs="unbounded" >
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="movieTitle" type="title"/>
                            <xs:element name="movieGenre" type="xs:string"/>
                            <xs:element name="movieReleaseDate" type="movieReleaseDate"/>
                            <xs:element name="moviePrice" type="moviePrice"/>
                            <xs:element name="availableCopies" type="availableCopies"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== alcorpisces/OMS/web/WEB-INF/movies.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<movies xmlns="http://learn.it.uts.edu.au/wsd"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://learn.it.uts.edu.au/wsd movies.xsd">

    <movie>
        <movieTitle>John Cena</movieTitle>
        <movieGenre>Action</movieGenre>
        <movieReleaseDate>2018-12-12</movieReleaseDate>
        <moviePrice>$40</moviePrice>
        <availableCopies>80</availableCopies>
    </movie>
    <movie>
        <movieTitle>Mission Impossible</movieTitle>
        <movieGenre>Action</movieGenre>
        <movieReleaseDate>2018-09-14</movieReleaseDate>
        <moviePrice>$45</moviePrice>
        <availableCopies>130</availableCopies>
    </movie>
</movies>
