=== alcorpisces/OMS/build/web/WEB-INF/users.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://learn.it.uts.edu.au/wsd"
           xmlns="http://learn.it.uts.edu.au/wsd"
           elementFormDefault="qualified">
    
    <xs:simpleType name="email">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z\._]+[@][a-z]+([\.][a-z-]+)+"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="name">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z][a-zA-Z]*([ ][A-Z][a-zA-Z]*)*"/>
        </xs:restriction>
    </xs:simpleType>
    
     <xs:simpleType name="phoneNumber">
        <xs:restriction base="xs:integer">
            <xs:pattern value="[0-9]*"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="users">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="email" type="email"/>
                            <xs:element name="name" type="name"/>
                            <xs:element name="password" type="xs:string"/>
                            <xs:element name="phoneNumber" type="phoneNumber"/>
                            <xs:element name="address" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== alcorpisces/OMS/web/WEB-INF/users.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<?xml-stylesheet type="text/xsl" href="users.xsl"?>
<users xmlns="http://learn.it.uts.edu.au/wsd"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://learn.it.uts.edu.au/wsd users.xsd">
    <user>
        <email>ryan@ryanheise.com</email>
        <name>Ryan Heise</name>
        <password>1234</password>
        <phoneNumber>0412824952</phoneNumber>
        <address>15 Johnson st, Sydney, NSW, 2000</address>
    </user>
    <user>
        <email>joe@bloggs.com</email>
        <name>Joe Bloggs</name>
        <password>foobar</password>
        <phoneNumber>0412345678</phoneNumber>
        <address>123 Hill st, Sydney, NSW, 2000</address>
    </user>
</users>
